apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: health-research-agent-api
  annotations:
    run.googleapis.com/ingress: internal-and-cloud-load-balancing  # Restrict to internal + LB
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cloudsql-instances: expanded-origin-464315-i8:europe-north1:agent-dev-sql
        run.googleapis.com/cpu-throttling: "true"  # Enable throttling for cost savings
        run.googleapis.com/memory: "512Mi"         # Reduce memory
        run.googleapis.com/cpu: "1000m"            # 1 CPU required for gen2
        run.googleapis.com/min-instances: "0"      # Scale to zero when idle
    spec:
      containerConcurrency: 10                     # Higher concurrency for better resource utilization
      timeoutSeconds: 60                           # Shorter timeout unless long tasks are expected
      containers:
      - image: gcr.io/expanded-origin-464315-i8/health-research-agent-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: PRINT_ENV_ON_LOAD
          value: "true"
        - name: WAIT_FOR_DB
          value: "true"
        - name: DB_HOST
          value: "/cloudsql/expanded-origin-464315-i8:europe-north1:agent-dev-sql/.s.PGSQL.5432"
        - name: DB_PORT
          value: "5432"
        - name: CLOUD_SQL_CONNECTION_NAME
          value: "expanded-origin-464315-i8:europe-north1:agent-dev-sql"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: DB_PASSWORD
              key: "1"
        - name: DB_DATABASE
          value: "postgres"
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: GOOGLE_API_KEY
              key: "1"
        - name: AGNO_API_KEY
          valueFrom:
            secretKeyRef:
              name: AGNO_API_KEY
              key: "1"
        - name: AGNO_MONITOR
          value: "True"
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi

